services:
  backend:
    build: ./backend_files
    ports:
      - "7860:7860"
  frontend:
    build: ./frontend_files
    environment:
      BACKEND_URL: http://backend:7860
    ports:
      - "8501:8501"
    depends_on:
      - backend
